###########################################################
### Long Vu â€“ Beautiful Jekyll config
###########################################################

############################
# --- Required options --- #
############################

# Name of website
title: Resume

# Your name to show in the footer
author: Long Vu

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  # Resume: "resume"
  # Blog: "blog"
  # About Me: "aboutme"

################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: '/assets/img/avatar-icon.png'

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: 'vuthanglonghd@gmail.com'
  telephone: '+14047064868'
  # rss: true
  github: longthangvu
  linkedin: long-vu-b35089289
  google-scholar: QmKHRIAAAAAJ
  ORCID: '0009-0007-6340-2233'

# RSS feed description
rss-description: 'Personal website with my resume and blog posts.'

###########################
# --- General options --- #
###########################

# Select which social network share links to show in posts
share-links-active:
  twitter: false
  facebook: false
  linkedin: true
  vk: false
  reddit: false

# How to display the link to your website in the footer
url-pretty: 'Main Page'

# Add the website title to the title of every page
title-on-all-pages: true

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: false

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
edit_page_button: true

# Allow sub-menu items (second-level navigation menu items) to be longer than the top-level menu
navbar-var-length: false

# The keywords to associate with your website, for SEO purposes
#keywords: "my,list,of,keywords"

######################################
# --- Colours / background image --- #
######################################

page-col: '#FFFFFF'
text-col: '#404040'
link-col: '#008AFF'
hover-col: '#0085A1'
navbar-col: '#EAEAEA'
navbar-text-col: '#404040'
navbar-border-col: '#DDDDDD'
footer-col: '#EAEAEA'
footer-text-col: '#777777'
footer-link-col: '#404040'
footer-hover-col: '#0085A1'

# Suggest a colour for mobile browsers to use as the browser's theme.
# (Use the same as your link colour for consistency.)
mobile-theme-col: '#008AFF'

# Extra CSS/JS for custom styling and dark mode
# site-css:
#   - '/assets/css/custom-styles.css'
#   - '/assets/css/darkmode.css'

# site-js:
#   - '/assets/js/darkmode.js'

#################################
# --- Web Analytics Section --- #
#################################

#gtag: "G-XXXXXXXXXX"
#cloudflare_analytics: ""
#gtm: ""

#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

#google_analytics: "UA-XXXXXXXX-X"

####################
# --- Comments --- #
####################

#disqus: ""
#fb_comment_id: ""
#commentbox: ""

#utterances:
#  repository:
#  issue-term: title
#  theme: github-light
#  label: blog-comments

#staticman:
#  repository:
#  branch: master
#  endpoint:
#  reCaptcha:
#    siteKey:
#    secret:

#giscus:
#  hostname: giscus.app
#  repository:
#  repository-id:
#  category: Announcements
#  category-id:
#  mapping: pathname
#  reactions-enabled: 1
#  emit-metadata: 0
#  theme: light

################
# --- Misc --- #
################

# Ruby Date Format to show dates of posts
date_format: '%B %-d, %Y'

# Facebook App ID
#fb_app_id: ""

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

# Output options (more information on Jekyll's site)
timezone: 'America/New_York'
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      comments: true
      social-share: true
  - scope:
      path: ''
    values:
      layout: 'page'

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
